extends "res://tests/framework/ui_test_case.gd"

## Behaviour of the home screen's action sheet.
##
## The eleven activity buttons used to sit inline in the column, which took 900px
## of an 1920px screen, squeezed the room scene to nothing and pushed the last row
## off the bottom edge. They now live in a sheet that slides up when ACTIONS is
## pressed. These tests pin the open/close paths, because a sheet that can be
## opened but not closed is a trap with no way out.

const HOME_SCENE := "res://ui/screens/home_screen.tscn"
## Preloaded rather than reached through the global class name, so these tests do
## not depend on Godot's class cache having been regenerated by an editor run.
const HomeScreenScript := preload("res://ui/screens/home_screen.gd")

var _home: Control = null


func before_each() -> void:
	_home = mount(HOME_SCENE) as Control


func _sheet() -> Control:
	return _home.get_node("Sheet") as Control


func _action_bar() -> Button:
	return _home.get_node("ActionBar") as Button


func _close_button() -> Button:
	return _home.get_node("Sheet/Panel/Pad/Body/Header/Close") as Button


func _menu() -> GridContainer:
	return _home.get_node("Sheet/Panel/Pad/Body/Menu") as GridContainer


# --- structure ---------------------------------------------------------------

func test_the_action_bar_is_anchored_to_the_bottom_of_the_window() -> void:
	# It must not ride inside the padded column, or it floats above the bottom
	# edge instead of sitting flush against it.
	var bar := _action_bar()
	assert_eq(bar.get_parent(), _home, "the action bar should hang off the screen root")
	assert_almost_eq(bar.anchor_top, 1.0, 0.001, "action bar is not bottom-anchored")
	assert_almost_eq(bar.anchor_bottom, 1.0, 0.001, "action bar is not bottom-anchored")
	assert_true(bar.offset_top < 0.0, "a bottom-anchored bar needs a negative top offset")


func test_the_sheet_holds_every_menu_slot() -> void:
	var count := _menu().get_child_count()
	assert_eq(count, HomeScreenScript.MenuSlot.size(),
		"the grid has %d buttons but MenuSlot declares %d" % [
			count, HomeScreenScript.MenuSlot.size()])


func test_the_stat_card_is_not_hidden_behind_the_action_bar() -> void:
	var root := _home.get_node("Root") as MarginContainer
	var bottom_margin := root.get_theme_constant("margin_bottom")
	var bar_height := absf(_action_bar().offset_top)
	assert_true(float(bottom_margin) >= bar_height,
		"the column reserves %dpx at the bottom for a %.0fpx bar" % [
			bottom_margin, bar_height])


# --- opening and closing -----------------------------------------------------

func test_the_sheet_starts_closed() -> void:
	assert_false(_sheet().visible, "the sheet should not be up when the screen opens")


func test_pressing_actions_opens_the_sheet() -> void:
	press(_action_bar())
	assert_true(_sheet().visible, "ACTIONS did not raise the sheet")


func test_the_close_button_shuts_the_sheet() -> void:
	press(_action_bar())
	press(_close_button())
	assert_false(_home.on_back_requested(),
		"after closing, back should fall through to the router again")


func test_tapping_the_scrim_shuts_the_sheet() -> void:
	# The gesture anyone who has used a phone tries first.
	press(_action_bar())
	var scrim := _home.get_node("Sheet/Scrim") as ColorRect
	var tap := InputEventMouseButton.new()
	tap.button_index = MOUSE_BUTTON_LEFT
	tap.pressed = true
	scrim.gui_input.emit(tap)
	assert_false(_home.on_back_requested(),
		"tapping outside the panel should have closed the sheet")


func test_back_closes_the_sheet_instead_of_leaving_the_screen() -> void:
	press(_action_bar())
	assert_true(_home.on_back_requested(),
		"with the sheet up, back should be consumed by the sheet")


func test_back_is_not_swallowed_when_the_sheet_is_shut() -> void:
	assert_false(_home.on_back_requested(),
		"with the sheet down, back belongs to the router")


func test_opening_twice_does_not_stack_tweens() -> void:
	# Two tweens fighting over the same offset leaves the panel stranded
	# mid-slide, which reads as a broken screen.
	press(_action_bar())
	press(_action_bar())
	assert_true(_sheet().visible, "the sheet should still be up after a double tap")
	assert_true(_home.on_back_requested(), "and should still be closable")


func test_choosing_an_activity_shuts_the_sheet() -> void:
	# Every entry either pushes a screen or spends a slot, so leaving the sheet
	# up would put it over whatever comes back.
	press(_action_bar())
	var rest := _menu().get_child(HomeScreenScript.MenuSlot.REST) as Button
	press(rest)
	assert_false(_home.on_back_requested(),
		"picking an activity should have closed the sheet")


func test_sparring_is_disabled_rather_than_missing() -> void:
	# Dossier §4 [C] and §14: dropping sparring is the single most-repeated error
	# about this game, so it stays in the menu, greyed, rather than being deleted.
	# The mission reskin renames the label; the slot must still be present, still
	# disabled, and still show the SPARRING activity's current display name.
	var sparring := _menu().get_child(HomeScreenScript.MenuSlot.SPARRING) as Button
	assert_true(sparring.disabled, "sparring is out of slice and should be disabled")
	var expected := Training.display_name(Training.Activity.SPARRING).to_upper()
	assert_true(sparring.text.to_upper().contains(expected),
		"the sparring slot should still name the SPARRING activity")
